package com.ldtteam.domumornamentum.datagen.global;

import net.minecraft.advancements.Advancement;
import net.minecraft.core.registries.MultiRegistryBootstrap;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.world.item.crafting.Recipe;

import java.util.function.BiFunction;

/**
 * MC 26.3: recipes (and their unlock advancements) are reloadable registry entries,
 * generated by bootstrapping a RegistrySetBuilder instead of a standalone DataProvider.
 */
public abstract class DomumRecipeProvider extends RecipeProvider {
    protected DomumRecipeProvider(BootstrapContext<Recipe<?>> recipes, BootstrapContext<Advancement> advancements) {
        super(recipes, advancements);
    }

    @Override
    protected abstract void buildRecipes();

    public static MultiRegistryBootstrap bootstrap(
        final BiFunction<BootstrapContext<Recipe<?>>, BootstrapContext<Advancement>, ? extends DomumRecipeProvider> factory)
    {
        return RecipeProvider.asBootstrap(factory);
    }
}
